basic:
  use_wandb: False
  device_map: auto
  offload_folder: ./offload
  output_dir: results
defaults:
  - _self_
  - model: hatebert
  - dataset: implicit_hate
  - prompt: defaults
hydra:
  job:
    chdir: False
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S.%f}